### ISSUE TITLE
ItemGib not working for some items

### ISSUE THREAD

**Issue by diogoo296** [The-Grand-Archives/Elden-Ring-CT-TGA#101]
Hi! The ItemGib script is not working for me for some items. I was able to add a Dagger, Talisman Pouch and Memory Stones, but none of the pots (Cracked, Ritual, Hefty) and the Perfume Bottles worked (I mean the containers, not the crafted item itself).

Here's the versions I'm using:
- App Ver. 1.13
- Calibrations Ver. 1.13.1
- Cheat Engine 7.5
- Cheat Table 1.14.1

**Comment by inuNorii** [comment]
Ah, looks like my check for `potGroupId` also counted the *containers* to their limits.
I'll fix that quickly.

**Comment by diogoo296** [comment]
Thanks, that was indeed quick :)

**Comment by brandonreynasw** [comment]
Still not working on 1.14.1 :(

**Comment by inuNorii** [comment]
This issue will be closed once a release with the fix is out.

**Comment by tomm1996** [comment]
If you want the pots to work on the current version, I did it like that:

- Openin the bottom most Menu in the table
- Misc/WIP -> Dependencies -> Double Click on <script> next to ItemGive_code
- Past in @inuNorii 's [updated code](https://raw.githubusercontent.com/The-Grand-Archives/Elden-Ring-CT-TGA/54b3c9bd4faafd4feb193f19ebee244776607f8e/CheatTable/CheatEntries/Open%20-%20The%20Grand%20Archives%20-%20Elden%20Ring/MiscWIP/Dependencies/Global%20Functions/ItemGive_code.cea) 
- File -> Save (name it TGA Fork or something)
- Restart CE, Load Table, Attach Process and try to drop Pots

Since this commit is not released yet, assume it's not stable code, I can only speak for myself when I say it worked and didn't break anything

**Comment by zeruzen** [comment]
> If you want the pots to work on the current version, I did it like that:
> 
> * Openin the bottom most Menu in the table
> * Misc/WIP -> Dependencies -> Double Click on <script> next to ItemGive_code
> * Paste in @inuNorii 's [updated code](https://raw.githubusercontent.com/The-Grand-Archives/Elden-Ring-CT-TGA/54b3c9bd4faafd4feb193f19ebee244776607f8e/CheatTable/CheatEntries/Open%20-%20The%20Grand%20Archives%20-%20Elden%20Ring/MiscWIP/Dependencies/Global%20Functions/ItemGive_code.cea)
> * File -> Save (name it TGA Fork or something)
> * Restart CE, Load Table, Attach Process and try to drop Pots
> 
> Since this commit is not released yet, assume it's not stable code, I can only speak for myself when I say it worked and didn't break anything

Probé tu procedimiento y funciona, gracias @tomm1996 @inuNorii 😃
