### ISSUE TITLE
Game Crash when clicking on Open

### ISSUE THREAD

**Issue by Pikselonix** [The-Grand-Archives/Elden-Ring-CT-TGA#28]

**Comment by tremwil** [comment]
First off, make sure you are using the latest version (1.1.2). If you are on the latest version, this could be due to patches fixing a bug in the C library not being applied. To apply them again, after opening the table (even if the game crashes, this will still work), clear the table's runOnce memory by going into `Table Tools -> Clear runOnce Memory -> Confirm`. Then restart the game and CE and try to open the table again.

If you are still getting crashes after this, please navigate to `C:\ProgramData\the-grand-archives\{your Windows username}\elden-ring\include\tga\` and verify that line 86 of `safe_ptr_read.h` starts with the following code: 
```c
requested_size |= 1;
while (!is_prime(requested_size)) {
    requested_size += 2;
}
``` 
If there is something at line 86 before this code block, then the table patches were not successfully applied, and we'll look into what could possibly be causing this. Otherwise, there may be another access violation or memory corruption bug in the C library. In that case please join our [discord server](https://discord.io/the-grand-archives) for live troubleshooting.
